### ISSUE TITLE
Questions and Suggestions

### ISSUE THREAD

**Issue by Paradox75831004** [LessonLethal/BetterUI#1]
A wonderful mod, especially hiding the chat. But I have a question, what does unlocking FPS affect? As soon as I added this mod to the build, my performance improved slightly, how is this possible? What does this mod do in general?

**Comment by Paradox75831004** [comment]
Can I contact you at the discord? It's more convenient to correspond there, if you don't mind

**Comment by Paradox75831004** [comment]
![image](https://github.com/LessonLethal/BetterUI/assets/72872478/cbea142d-2811-4a33-a68a-15f05483d6be)
Is it possible to link FPS unlock to these settings?

Uncapped

**Comment by tilergif** [comment]
> Can I contact you at the discord? It's more convenient to correspond there, if you don't mind

Of course, you're free to contact me on discord! @tyleroutcast

>Is it possible to link FPS unlock to these settings?
>Uncapped

Yes, it turns vSync off and it also raises the max FPS limit to 500.

**Comment by LessonLethal** [comment]
Closed issue after conversing, new updates already out to add config setting to control FrameRate/vSync.

**Comment by LessonLethal** [comment]
Closed issue after conversing, new updates already out to add config setting to control FrameRate/vSync.

**Comment by tilergif** [comment]
Closed issue after conversing, new updates already out to add config setting to control FrameRate/vSync.
